services:
  postgres:
    image: postgres:16-alpine
    container_name: she-ride-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: billie182001
      POSTGRES_DB: she_ride_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: